# Starter pipeline


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureSubscription: 'PCSDSM (6270c2d6-d30a-41ec-8edb-519b950de71b)'
      AuthenticationType: 'server'
      ServerName: 'demoforpcs'
      DatabaseName: 'MyDemo'
      SqlUsername: 'server_admin'
      SqlPassword: 'P@ssw0rd1!'
      deployType: 'SqlTask'
      SqlFile: 'PCS_Workshop.sql'
      IpDetectionMethod: 'AutoDetect'
