# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DevOpsSPN'
    subscriptionId: '156859c7-c94a-4494-a2fd-f3fb88d2316d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DemoDevOps'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.storage/storage-blob-container/azuredeploy.json'
    deploymentMode: 'Incremental'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

