# Starter pipeline


trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'DevOpsSPN'
    AuthenticationType: 'server'
    ServerName: 'auto-pcs-dwh-svr.database.windows.net'
    DatabaseName: 'EDS'
    SqlUsername: 'pcsdwadmin'
    SqlPassword: 'OgDE3v5W#8vb'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    SqlFile: '/data_factory_arm_template/eds_script.sql'
    IpDetectionMethod: 'AutoDetect'

