# Starter pipeline


trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'DevOpsSPN'
    AuthenticationType: 'server'
    ServerName: 'auto-pcs-dwh-svr.database.windows.net'
    DatabaseName: 'EDS'
    SqlUsername: 'pcsdwadmin'
    SqlPassword: 'OgDE3v5W#8vb'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    SqlFile: 'https://raw.githubusercontent.com/piscro/DemoPCS/main/eds.sql'
    IpDetectionMethod: 'AutoDetect'
    AdditionalArguments: '/TargetTimeout:3600 /p:CommandTimeout=3600'
